info:
  app:
    name: "Submissões de Artigos"
    description: "Projeto para submissões de artigos científicos em eventos"
    version: "0.0.1.SNAPSHOT"

spring:
  h2:
    console:
      enabled: true
      path: "/h2"
  datasource:
    url: "jdbc:h2:file:~/db/submissoes"
    username: "sa"
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      show_sql: true
      type: trace
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

gestao-vinhos:
  uploadFilePath: "/tmp/gestao-vinhos/files"
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health, env, metrics, sessions, mappings, info, liquibase"

